name: afectod
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #USER INTERFACE
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  lottie: ^3.3.2
  intl: any

  #ARCHITECTURE DEPENDENCIES
  auto_route: ^11.1.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.2
  url_launcher: ^6.3.2

  #STATE MANAGEMENT
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0

  #UTILS
  equatable: ^2.0.7
  path_provider: ^2.1.5
  package_info_plus: ^8.1.2

  #STORAGE
  shared_preferences: ^2.5.4
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.2.4
  build_runner: ^2.10.4
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.10.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/lotties/
