// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:afectod/app/features/data/models/auth/user_model.dart';
import 'package:afectod/app/features/data/models/favorites/favorite_list_model.dart';
import 'package:afectod/app/features/data/models/favorites/favorite_movie_model.dart';
import 'package:afectod/app/features/data/models/search/search_history_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteListModelAdapter());
    registerAdapter(FavoriteMovieModelAdapter());
    registerAdapter(SearchHistoryModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteListModelAdapter());
    registerAdapter(FavoriteMovieModelAdapter());
    registerAdapter(SearchHistoryModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
